### ISSUE TITLE
plugin.yml

### ISSUE THREAD

**Issue by Barlaf** [KairusDarkSeeker/KaiAuth#2]
Hello is possible to check my proposition of plugin.yml ?

**Comment by KairusDarkSeeker** [comment]
@Barlaf what?

**Comment by Barlaf** [comment]
I propose a new plugin.yml.
I changed the API

**Comment by Barlaf** [comment]
In the plugin.yml please add this:
- 3.0.0-ALPHA3
- 3.0.0-ALPHA3
- 3.0.0-ALPHA3
- 3.0.0-ALPHA3

**Comment by KairusDarkSeeker** [comment]
@Barlaf okay

**Comment by KairusDarkSeeker** [comment]
@Barlaf there's no ALPHA-6

**Comment by Barlaf** [comment]
Good thx :)

**Comment by KairusDarkSeeker** [comment]
@Barlaf np
